import Image from "next/image";
import type { InvoiceVerificationData } from "@/lib/invoice-verification/queries";

type InvoiceVerificationViewProps =
  | { data: InvoiceVerificationData; notFound?: false }
  | { notFound: true; data?: undefined };

function DetailRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="border-b border-[rgba(var(--gold-rgb),0.12)] py-3 last:border-b-0">
      <dt className="text-xs font-semibold uppercase tracking-wide text-[var(--color-text-secondary)]">
        {label}
      </dt>
      <dd className="mt-1 text-base text-[var(--color-text-primary)]">{value}</dd>
    </div>
  );
}

export function InvoiceVerificationView(props: InvoiceVerificationViewProps) {
  const notFound = "notFound" in props && props.notFound;

  return (
    <div className="tv-auth-page justify-center">
      <div className="mb-8">
        <Image
          src="/logo.png"
          alt="T-Vault"
          width={180}
          height={48}
          className="tv-brand-mark h-10 w-auto"
          priority
        />
      </div>

      <div className="w-full max-w-md rounded-2xl border border-[rgba(var(--gold-rgb),0.18)] bg-[var(--color-surface)] p-6 shadow-sm">
        <p className="text-xs font-semibold uppercase tracking-[0.12em] text-[rgb(var(--gold-rgb))]">
          Invoice Verification
        </p>

        {notFound ? (
          <>
            <h1 className="tv-page-title mt-2">Invoice not found</h1>
            <p className="tv-body mt-3 text-[var(--color-text-secondary)]">
              We could not find a T-Vault invoice matching this number. Check the
              QR code or invoice number and try again.
            </p>
          </>
        ) : (
          <>
            <h1 className="tv-page-title mt-2">{props.data.invoiceNumber}</h1>

            <div
              className="mt-5 rounded-xl border border-[rgba(var(--gold-rgb),0.25)] bg-[rgba(var(--gold-rgb),0.08)] px-4 py-3"
              role="status"
            >
              <p className="text-sm font-semibold text-[var(--color-text-primary)]">
                ✓ This invoice is valid and was generated by T-Vault
              </p>
            </div>

            <dl className="mt-6">
              <DetailRow label="Date generated" value={props.data.generatedDate} />
              <DetailRow label="Carrier" value={props.data.companyName} />
              <DetailRow
                label="Authority"
                value={[
                  props.data.mcNumber ? `MC# ${props.data.mcNumber}` : null,
                  props.data.dotNumber ? `DOT# ${props.data.dotNumber}` : null,
                ]
                  .filter(Boolean)
                  .join(" · ") || "—"}
              />
              <DetailRow label="Load route" value={props.data.routeLabel} />
              <DetailRow label="Total amount" value={props.data.totalAmount} />
            </dl>

            <p className="mt-6 text-xs text-[var(--color-text-secondary)]">
              This page confirms invoice details only. It does not provide access
              to the invoice PDF or other account records.
            </p>
          </>
        )}
      </div>

      <p className="mt-8 text-center text-xs text-[var(--color-text-secondary)]">
        Generated by T-Vault — A Dynasty Web Product
      </p>
    </div>
  );
}
