import { jsPDF } from "jspdf";
import type { TaxSummaryData } from "@/lib/tax-summary/calculations";
import { formatCurrency, formatCurrencyDetailed } from "@/lib/dashboard/format";

const ROWS_PER_PAGE = 25;
const MARGIN = 18;
const PAGE_W = 210;
const RIGHT_X = PAGE_W - MARGIN;

function addFooter(doc: jsPDF, page: number, totalPages: number): void {
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by T-Vault — A Dynasty Web Product", MARGIN, 285);
  doc.text(`Page ${page} of ${totalPages}`, RIGHT_X - 20, 285, { align: "right" });
}

export function generateTaxSummaryPdf(data: TaxSummaryData): void {
  const doc = new jsPDF();
  const jobPages = Math.max(1, Math.ceil(data.jobSummary.length / ROWS_PER_PAGE));
  const totalPages = jobPages + 1;

  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  doc.text("Tax Summary", MARGIN, 24);
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.text(data.range.label, MARGIN, 32);
  doc.text("For reference only. Consult a tax professional.", MARGIN, 38);

  let y = 50;
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Earned: ${formatCurrency(data.totalEarned)}`, MARGIN, y);
  y += 8;
  doc.text(`Total Expenses: ${formatCurrency(data.totalExpenses)}`, MARGIN, y);
  y += 8;
  doc.text(`Net Income: ${formatCurrency(data.netIncome)}`, MARGIN, y);
  y += 8;
  doc.text(`Miles Driven: ${data.milesDriven.toLocaleString()}`, MARGIN, y);
  y += 12;

  if (data.bestMonth) {
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(
      `Best month: ${data.bestMonth.label} — ${formatCurrency(data.bestMonth.amount)}`,
      MARGIN,
      y
    );
    y += 10;
  }

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text("Expense Breakdown", MARGIN, y);
  y += 8;
  data.expenseBreakdown.forEach((item) => {
    doc.text(
      `${item.category}: ${formatCurrency(item.amount)}`,
      MARGIN + 4,
      y
    );
    y += 6;
  });

  addFooter(doc, 1, totalPages);

  doc.addPage();
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Cost Per Mile Summary", MARGIN, 24);
  doc.setFontSize(11);
  y = 36;
  doc.text(
    `Revenue/Mile: ${formatCurrencyDetailed(data.costPerMile.revenuePerMile)}`,
    MARGIN,
    y
  );
  y += 8;
  doc.text(
    `Cost/Mile: ${formatCurrencyDetailed(data.costPerMile.costPerMile)}`,
    MARGIN,
    y
  );
  y += 8;
  doc.text(
    `Net/Mile: ${formatCurrencyDetailed(data.costPerMile.netPerMile)}`,
    MARGIN,
    y
  );
  y += 8;
  doc.text(
    `Total Miles: ${data.costPerMile.totalMiles.toLocaleString()}`,
    MARGIN,
    y
  );
  addFooter(doc, 2, totalPages);

  for (let page = 0; page < jobPages; page++) {
    doc.addPage();
    const pageNum = page + 3;
    doc.setFontSize(14);
    doc.text("Load by Load Summary", MARGIN, 20);
    doc.setFontSize(9);
    let rowY = 30;
    const slice = data.jobSummary.slice(
      page * ROWS_PER_PAGE,
      (page + 1) * ROWS_PER_PAGE
    );
    slice.forEach((row) => {
      doc.text(
        `${row.jobName} | ${row.completionDate} | Rev ${formatCurrency(row.revenue)} | Exp ${formatCurrency(row.expenses)} | Net ${formatCurrency(row.net)}`,
        MARGIN,
        rowY
      );
      rowY += 6;
    });
    addFooter(doc, pageNum, totalPages);
  }

  doc.save(`tvault-tax-summary-${data.range.start}.pdf`);
}
